config/routes.rb
Rails.application.routes.draw do

  
  root 'static_pages#index'
  resources :publication_types
  resources :publications , except: :destroy
  resources :publication_subtypes
  resources :publication_attributes
  resources :authors

  get 'admin/users/index' , to: 'admins#users' , as: :users_administrator
  delete 'admin/users/:id/destroy' , to: 'admins#destroy_user' , as: :admin_destroy_user
  get 'admin/users/:id/edit', to: 'admins#edit_user' , as: :admin_edit_user
  patch 'admin/users/:id' , to: 'admins#update_user' , as: :admin_user

  match 'attributes/:subtype/:publication' , to: 'publications#params_list' , via: 'get'
  match 'attributes/:subtype' , to: 'publications#params_list_new', via: 'get'
  devise_for :users , controllers: {registrations: "users/registrations"}

end

app/views/admins/edit_user.html.erb
<h1> Edycja użytkownika </h1>

<div class="row">
<div class="col-md-8">
<div class="panel panel-default">
<div class="panel-heading">
 <%= @user.full_name %>
</div>
<div class="panel-body">
<%= bootstrap_form_for @user , url: {action: "update_user" , controller: "admins"} do |u| %>
	<strong>Parametry konta: </strong>
	<%= u.check_box  :admin , label: "Administrator" %>
	<%= u.check_box  :approved , label: "Konto aktywne" %>
	<%= u.check_box  :reminder, label: "Przypomnienie" %>
	<%= u.text_field :date_reminder ,label: "Data przypomnienia - od" %>
	<%= u.text_field :date_reminder_last ,label: "Data przypomnienia - do" %>
	<%= u.submit "Zapisz zmiany" , class: "btn btn-primary" %>
<% end %>
</div>
</div>
</div>
</div>

app/views/admins/users.html.erb
<h1> Lista użytkowników </h1>

<div class="panel panel-default" >

<table class="table">

<thead>
	<tr>
		<th>Nazwisko i imię </th>
		<th>Adres email</th>
		<th>Administrator</th>
		<th>Konto aktywne</th>
		<th>Przypomnienie</th>
		<th></th>
	</tr>
</thead>

<tbody>
<% if @users.size > 0%>
	<% @users.each do |u| %>
		<tr>
			<td><%= "#{u.author.academic_degree} #{u.author.surname} #{u.author.name}" %></td>
			<td><%= u.email %></td>
			<td><%= yes_or_no u.admin %></td>
			<td><%= yes_or_no u.approved %></td>
			<td><%= yes_or_no u.reminder %></td>
			<td>
				<%= link_to "Usuń",admin_destroy_user_path(u),method: :delete, data: { confirm: 'Are you sure?' } %>| 
				<%= link_to "Edytuj" ,admin_edit_user_path(u)  %>
			</td>
		</tr>	
	<% end %>
<% else %>
	<tr><td>No other users found. </td></tr>
<% end %>
</tbody>


</table>


</div>