config/routes.rb
Rails.application.routes.draw do

  
  root 'static_pages#index'
  resources :publication_types
  resources :publications , except: :destroy
  resources :publication_subtypes
  resources :publication_attributes
  resources :authors

  get 'admin/users/index' , to: 'admins#users' , as: :users_administrator
  delete 'admin/users/:id/destroy' , to: 'admins#destroy_user' , as: :admin_destroy_user
  get 'admin/users/:id/edit', to: 'admins#edit_user' , as: :admin_edit_user
  patch 'admin/users/:id' , to: 'admins#update_user' , as: :admin_user

  match 'attributes/:subtype/:publication' , to: 'publications#params_list' , via: 'get'
  match 'attributes/:subtype' , to: 'publications#params_list_new', via: 'get'
  devise_for :users , controllers: {registrations: "users/registrations"}

end

app/controllers/publication_subtypes_controller.rb
class PublicationSubtypesController < ApplicationController
  before_action :set_publication_subtype, only: [:show, :edit, :update, :destroy]
  # GET /publication_subtypes
  # GET /publication_subtypes.json
  def index
    @publication_subtypes=PublicationSubtype.joins(:publication_type)
                                .order("publication_types.name ASC").order("name ASC")
  end

  # GET /publication_subtypes/1
  # GET /publication_subtypes/1.json
  def show
  end

  # GET /publication_subtypes/new
  def new
    authorize! :create , PublicationSubtype
    @subtype = PublicationSubtype.new
    setup_type_options
  end

  # GET /publication_subtypes/1/edit
  def edit
    authorize! :edit, @subtype
    setup_type_options
  end

  # POST /publication_subtypes
  # POST /publication_subtypes.json
  def create
    authorize! :create , PublicationSubtype
   respond_to do |format|
      @subtype = PublicationSubtype.new(name: params[:name], publication_type_id: PublicationType.getId(params[:kind]))
      if @subtype.save
        format.html { redirect_to publication_subtypes_path, notice: 'Publication subtype was successfully created.' }
        format.json { render :show, status: :created, location: @subtype }
      else
        setup_type_options
        flash[:danger] = @subtype.errors.full_messages
        format.html { render :new }
        format.json { render json: @subtype.errors, status: :unprocessable_entity }
      end
    end
  end

  def update 
    authorize! :edit , @subtype
    @subtype.publication_type_id = PublicationType.getId(params[:kind]) 
    @subtype.name=params[:name]
    respond_to do |format|
      if @subtype.save
        format.html { redirect_to @subtype, notice: 'Publication subtype was successfully updated.' }
        format.json { render :show, status: :ok, location: @subtype }
      else
        setup_type_options
        format.html { render :edit }
        format.json { render json: @subtype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publication_subtypes/1
  # DELETE /publication_subtypes/1.json
  def destroy
    authorize! :destroy , @subtype
    @subtype.destroy
    respond_to do |format|
      format.html { redirect_to publication_subtypes_url, notice: 'Publication subtype was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication_subtype
      @subtype = PublicationSubtype.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_subtype_params
      params.require(:publication_subtype).permit(:name,:publication_type_id)
    end
    
    def setup_type_options
      @subtype_list = PublicationSubtype.uniq.pluck(:name)
      @type_list = PublicationType.pluck(:name)
    end
end

app/helpers/publication_subtypes_helper.rb
module PublicationSubtypesHelper
end

app/views/publication_subtypes/_form.html.erb
<div class="row">
  <div class = "col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <%=title%>

      </div>
      <div class="panel-body">
        <%= bootstrap_form_for(@subtype) do |f| %>
          <div class="form-group">
            <label>Typ publikacji</label>
            <input list="types" class="form-control" name= "kind" autocomplete="off"
              value="<%= @subtype.publication_type_name %>">
            <datalist id="types">
              <% @type_list.each do |n|%>
                <option value="<%= n %>"></option>
              <% end %>
            </datalist>
          </div>
          <div class="form-group">
            <label>Podtyp publikacji</label>
            <input list="name" class="form-control" name="name" autocomplete="off"
              value="<%= @subtype.name %>">
            <datalist id="name">
              <% @subtype_list.each do |n|%>
                <option value="<%= n %>"></option>
              <% end %>
            </datalist>
          </div>
          <%= f.submit "Zapisz" %>
        <% end %>
      </div>
      <div class="panel-footer">
        <%= link_to 'Back', publication_subtypes_path,class: "label label-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/publication_subtypes/edit.html.erb
<h1>Edycja podtypu publikacji</h1>
<%= render partial: 'form' , locals: {title:  @subtype.full_name } %>

app/views/publication_subtypes/index.html.erb
<h1>Lista rodzajów publikacji</h1>

<div class="row">
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <strong>Liczba elementów: </strong><%= @publication_subtypes.count %>
          <%= link_to 'Nowy podtyp', new_publication_subtype_path  ,class: "pull-right label label-default" if can? :create , PublicationSubtype %>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>Typ</th>
              <th>Podtyp</th>
              <th>Akcje</th>
            </tr>
          </thead>
          <tbody>
            <% @publication_subtypes.each do |publication_subtype| %>
              <tr>
                <td> <%=link_to publication_subtype.publication_type_name, publication_subtype.publication_type %></td>
                <td> <%=publication_subtype.name%></td>
                <td><%= link_to 'Pokaż', publication_subtype %>
                <%= link_to 'Edytuj', edit_publication_subtype_path(publication_subtype) if can? :edit, PublicationSubtype %>
                <%= link_to 'Usuń', publication_subtype, method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy , publication_subtype %></td>
              </tr>
             <% end %>
          </tbody>
        </table>
        <div class="panel-footer">
        </div>
      </div>
  </div>
</div>

<!--  -->

app/views/publication_subtypes/new.html.erb
<h1>Nowy rodzaj publikacji</h1>
<%= render partial: 'form' , locals: {title: "Dane dla nowego podtypu"} %>

app/views/publication_subtypes/show.html.erb
<div class="row">
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<%= link_to "Edycja" , edit_publication_subtype_path(@subtype) ,
					class: "label label-primary" if can? :edit , @subtype %>
			</div>
			<div class="panel-body">
				<strong>Nazwa: </strong><%= @subtype.full_name %>
			</div>
			<div class="panel-footer">
				<%= link_to "Lista podtypów" , publication_subtypes_path , class: "label label-primary" %>
			</div>
		</div>
	</div>
</div>