config/routes.rb
Rails.application.routes.draw do

  
  root 'static_pages#index'
  resources :publication_types
  resources :publications , except: :destroy
  resources :publication_subtypes
  resources :publication_attributes
  resources :authors

  get 'admin/users/index' , to: 'admins#users' , as: :users_administrator
  delete 'admin/users/:id/destroy' , to: 'admins#destroy_user' , as: :admin_destroy_user
  get 'admin/users/:id/edit', to: 'admins#edit_user' , as: :admin_edit_user
  patch 'admin/users/:id' , to: 'admins#update_user' , as: :admin_user

  match 'attributes/:subtype/:publication' , to: 'publications#params_list' , via: 'get'
  match 'attributes/:subtype' , to: 'publications#params_list_new', via: 'get'
  devise_for :users , controllers: {registrations: "users/registrations"}

end

app/models/publication.rb
class Publication < ActiveRecord::Base
	include PublicActivity::Model

	after_create :remove_reminder

  	tracked except: :destroy, owner: Proc.new{ |controller, model| controller.current_user }
	has_many :attribute_values , inverse_of: :publication , :dependent => :destroy
	has_many :author_positions , inverse_of: :publication , :dependent => :destroy
	has_many :authors , through: :author_positions
	belongs_to :publication_subtype
	belongs_to :user
	validates :title, :description, :user, :publication_subtype,:publish_at, presence: true
	has_attached_file :zalacznik , :url  => "/assets/publications/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/publications/:id/:style/:basename.:extension"
    validates_attachment_content_type :zalacznik, :with => %r{\.(docx|doc|pdf)$}i ,
      :content_type => [ "application/pdf","application/vnd.ms-excel",     
             "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
             "application/msword", 
             "application/vnd.openxmlformats-officedocument.wordprocessingml.document", 
             "text/plain" ]

	accepts_nested_attributes_for :author_positions
	accepts_nested_attributes_for :attribute_values

	default_scope {order('created_at DESC')}

	searchable do
		text :title
		text :description
		integer :publication_subtype_id
		integer :user_id 
		integer :publish_at
		integer :author_ids, multiple: true do
			authors.map {|author| author.id }
		end

		text :authors do
			authors.map {|author| author.full_name}
		end
		text :type do
			publication_subtype.full_name
		end
		time :created_at
	end

	def self.form_attributes
		publication_subtype.publication_type.publication_attributes
	end

	def biblio_authors
		string = ""
		authors.each do |a|
			string+=a.biblio_name+", "
		end
		return string
	end

	def set_values arguments
		attributes = []
		publication_subtype.get_attributes.each do |attr|
			val = arguments["#{attr.id}"] unless arguments == nil
			raise "Error. Missing argument for #{attr.name} attribute" if val == nil
			value = AttributeValue.new(publication_attribute: attr, 
			attribute_value: val, publication: self)
			attributes << value
		end if publication_subtype
		attribute_values = []
		self.attribute_values = attributes
	end

	def attrs_values subtype_id
		if publication_subtype.id == subtype_id
      		arry = {}
      		attribute_values.each do |f|
      			arry[f.publication_attribute.id]=f.attribute_value
      		end
      		return arry
    	else
      		return []
    	end
	end

	def self.do_search search, publish_date, user_only, author_id, format, page
		count = Publication.count if format
		@search = Publication.search do
	      fulltext search do
	        phrase_fields title: 3.0
	        fields(:authors,:title,:type)
	      end
	      order_by :publication_subtype_id, :asc if format
	      order_by :publish_at, :desc
	      with :user_id, user_only  if user_only
	      with :publish_at, publish_date.to_i if publish_date && publish_date!=""
	      with :author_ids, author_id if author_id
	      paginate( page.to_i ) if page && page!="" if !format
	      paginate( page: 1, per_page: count ) if format
	    end
	end

	private 
		def remove_reminder
			self.user.update_attributes(date_reminder: nil , reminder: false)
		end
	
end

app/models/publication_type.rb
class PublicationType < ActiveRecord::Base
	has_many :publication_subtypes , :inverse_of=> :publication_type, :dependent => :destroy
	has_many :attribute_positions , inverse_of: :publication_type, :dependent => :destroy
	has_many :publication_attributes, through: :attribute_positions
	accepts_nested_attributes_for :attribute_positions
	validates :name , presence: true , uniqueness: true
	
	def self.getId name
		p = PublicationType.where(name: name).first
		if p == nil
			d = PublicationType.new(name: name)
			d.save
			return d.id
		else
			return p.id
		end
	end


	def self.prepare_type_list
		types = PublicationType.all.order("name ASC")
		ary = Array.new
		types.each do |t|
			t.publication_subtypes.each do |s|
				ary<<["#{t.name} - #{s.name}",s.id]
			end
		end
		return ary
	end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  include ApplicationHelper
  before_action :set_publication, only: [:show, :edit, :update, :destroy]
  #
  respond_to :docx

  # GET /publications
  # GET /publications.json
  def index
    authorize! :read , Publication
    @search = Publication.do_search(
        params[:search], params[:publish_at],
        only_current_user(params[:only_me]), nil, params[:format]=="pdf",params[:page]
      )
    
    @publications = @search.results
    respond_to do |format|
      format.pdf do
        render :pdf => "file_name", 
        :template => 'publications/index.pdf.erb',
        :encoding  => "UTF-8"
      end
      format.html 
    end
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
    @publication = Publication.find(params[:id])
    authorize! :read , @publication   

    respond_to do |format|
     format.pdf do
        render :pdf => "file_name", 
        :template => 'publications/show.pdf.erb',
        :encoding  => "UTF-8"
      end
      format.docx do
      render docx: 'my_view', filename: 'my_file.docx'
      # Alternatively, if you don't want to create the .docx.erb template you could
      # render docx: 'my_file.docx', content: '<html><body>some html</body></html>'
    end
      format.html
   end
  end

  # GET /publications/new
  def new
    authorize! :create , Publication
    @publication = Publication.new
    @authors = Author.prepare_seletc_array
    @types = PublicationType.prepare_type_list
    @selected = []
    @type = []
  end

  def params_list_new
    @subtype = PublicationSubtype.find(params[:subtype])
    @values = []
    respond_to do |format|
      format.js
    end
  end

  def params_list
    @subtype = PublicationSubtype.find(params[:subtype])
    publication = Publication.find(params[:publication])
    @values = publication.attrs_values @subtype.id
     respond_to do |format|
      format.js {render 'params_list_new'}
    end
  end

  # GET /publications/1/edit
  def edit
    @publication = Publication.find(params[:id])
    authorize! :edit ,  @publication
    @authors = Author.prepare_seletc_array
    @types = PublicationType.prepare_type_list
    @type = @publication.publication_subtype.id
    @selected = @publication.authors.pluck(:id)
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(publication_params)
    authorize! :create , Publication
    @publication.user = current_user
    @publication.authors = Author.where(id: params[:publication][:authors][:id])
    @publication.set_values params[:attribute]
    respond_to do |format|
      if @publication.save
        format.html { redirect_to publications_path, notice: 'Publication was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        @authors = Author.prepare_seletc_array
        @types = PublicationType.prepare_type_list
        flash[:danger] = @publication.errors.full_messages
        @type = params[:publication][:publication_subtype_id]
        @selected = params[:publication][:authors][:id]
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    authorize! :edit ,  @publication
    @publication.attributes = publication_params
    @publication.authors = Author.where(id: params[:publication][:authors][:id])
    @publication.set_values params[:attribute]
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
         @authors = Author.prepare_seletc_array
        @types = PublicationType.prepare_type_list
        flash[:danger] = @publication.errors.full_messages
        @type = params[:publication][:publication_subtype_id]
        @selected = params[:publication][:authors][:id]
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    authorize! :destroy, @publication
    @publication.create_activity :destroy , info: @publication.title, owner: current_user
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_params
      params.require(:publication).permit(:title, :description, :publication_subtype_id,:zalacznik,:publish_at)
    end
end
#

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_additional_attr.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		Dodatkowe paremtry
	</div>
	<div class="panel-body" id="attributes_list">
		Brak
	</div>
</div>

app/views/publications/_form.html.erb
  <div class="row">
    <div class="col-md-6">
    <%= bootstrap_form_for(@publication , html: {id: "main_form"} ) do |f| %>
      <%= render partial: 'simple_form' , locals: {f: f} %>
      <%= f.submit "Zapisz" %>
    </div>
    <div class="col-md-6">
      <%= render partial: 'additional_attr' %> 
    </div>
    <input type="text" hidden="true" id="pub_id" value="<%= @publication.id %>">
  </div>
  
<% end %>

app/views/publications/_publication.html.erb
<li class="list-group-item libib">
  <span class="pull-right label label-success">
    <%= link_to fa_icon("file", text: "Pokaż"), publication if can? :read , publication %>
    <%= link_to fa_icon("remove", text: "Usuń"), publication, method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy , publication %>
  </span>  
  <span class="pull-right label label-default">
    <%= publication.user.email %> 
  </span>
  <span>
    <%= publication.biblio_authors %>,
    <i> <%= link_to publication.title , publication %>, </i>
    <%= publication.publish_at %>, 
    <%=publication.publication_subtype.full_name%>.
  </span>     
</li>

app/views/publications/_show.docx.erb
<h1>a</h1>

app/views/publications/_showpublist.html.erb
 
<div >
<% prev = nil %>
<% @publications.each do |p| %>
	<% new_one = (prev!=p.publication_subtype_id) %>
	<% if prev!=nil && new_one %> </ol> <% end %>
	<% if new_one %>
	   <h4><%= p.publication_subtype.full_name("") %></h4>
	   <ol> 
	<% end %>
   		 <li> <%=p.biblio_authors%> <q> <i><%=p.title%> </i> </q>,
   		  <%=p.publish_at %>.
   		 </li>
  
    <% prev = p.publication_subtype_id %>
<% end %>
<% if @publications.any? %>
	</ol>
<% else %>
	Brak publikacji.
<% end %>
</div>

app/views/publications/_simple_form.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		Dane podstawowe
	</div>
	<div class="panel-body">
		<%= f.text_field :title , required: true , label: "Tytuł publikacji" %>
		<%= f.text_field :description , required: true , label: "Opis" %>
		<%= f.select(:publication_subtype_id,options_for_select(@types,@type),{ required: true, label: "Typ"},{ id: "type_select"} ) %>

		<%= f.fields_for :authors do |a| %>
			<%= a.select(:id,options_for_select(@authors,@selected),{label: "Autorzy"},{multiple: true , id: "author_select"}) %>
		<div class="form-group">
			<%= f.label :publish_at ,"Rok wydania" %>
			<%= select_year Date.today, {:start_year => Time.now.year, :end_year => Time.now.year - 95, :field_name => 'publish_at'} , {:class=>"form-control",:name=>"publication[publish_at]"}  %>
		</div>
		<%= f.file_field :zalacznik , label: "Wersja elektroniczna: " %>
		<% end %>
	</div>
</div>

app/views/publications/edit.html.erb
<h1>Edycja</h1>

<div class="panel panel-default">
	<div class="panel-body">
		<%= render 'form' %>
	</div>
	<div class="panel-footer">
		<%= link_to 'Back', publications_path %>
	</div>
</div>

app/views/publications/header.pdf.erb
<% if params[:format] && params[:format] == 'pdf' %>
  <%= wicked_pdf_stylesheet_link_tag 'application' %>
<% else %>
  <%= stylesheet_link_tag 'application' %>
<% end %>

<div class="document">
    <%= render :partial => 'publications/header.html.erb' %>
</div>

app/views/publications/index.html.erb
<h3></h3>
<div class="row">
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <strong>Lista publikacji</strong>
         <%= render 'shared/pdf_link' %>
         <%= link_to 'Nowa publikacja', new_publication_path , class: "label label-primary pull-right" if can? :create , Publication  %>
      </div>
      <% if @publications.any? %>
        <ul class="list-group">
          <%= render @publications %>
        </ul>
      <% else %>
        <div class="panel-body"> Brak publikacji </div>
      <% end %>
      <div class="panel-footer">   
        <%= will_paginate @search.hits %> 
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading"><strong>Wyszukiwanie</strong></div>
      <div class="panel-body">
        <%= render  'shared/search_form' %>
      </div>
      <div class="panel-footer">

      </div>
    </div>
  </div>
</div>

<br>


<!--  -->

app/views/publications/index.pdf.erb
<% if params[:format] && params[:format] == 'pdf' %>
  <%= wicked_pdf_stylesheet_link_tag 'application' %>
<% else %>
  <%= stylesheet_link_tag 'application' %>
<% end %>

<div class="document" style="margin:30px 50px 10px 50px">
<h1 ><img src="http://www.robo.prz-rzeszow.pl/KIA-LOGO.GIF"> Lista publikacji </h1>
    <%= render :partial => 'publications/showpublist.html.erb' %>
</div>

app/views/publications/my_view.docx.erb
<h1> My custom template </h1>

app/views/publications/params_list_new.js.erb
$("#attributes_list").html("<%= escape_javascript(render 'attributes') %>");

app/views/publications/show.docx.erb
<h1><img src="http://www.robo.prz-rzeszow.pl/KIA-LOGO.GIF"> Informacje o publikacji </h1>

<div class ="row">
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<strong>Tytuł: </strong><%= @publication.title %>
			</div>
			
			<ul class="list-group">
			<li class="list-group-item"><strong>Typ: </strong><%= @publication.publication_subtype.full_name %></li>
			<li class="list-group-item"><strong>Opis: </strong><%= @publication.description %></li>
			<li class="list-group-item"><strong>Rok wydania: </strong><%= @publication.publish_at %></li>
			<li class="list-group-item">
				<strong> Lista autorów: </strong>
				<ul class="list-group">
					<% @publication.authors.each do |a| %>
						<li class="list-group-item">
							<strong><%= "#{a.full_name}, " %></strong>
							<%= a.email %>
						</li>
					<% end %>
				</ul>
			</li>
			<li class="list-group-item"><strong>Dodane przez: </strong><%= "#{@publication.user.full_name} , #{@publication.user.email}" %></li>
			<li class="list-group-item"><strong>Data dodania: </strong><%= @publication.created_at %></li>
			<li class="list-group-item"><strong>Data aktualizacji: </strong><%= @publication.updated_at %></li>
			</ul>

					
		</div>
	</div>

	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				Dodatkowe parametry
			</div>
			<% if @publication.attribute_values.any? %>
				<ul class="list-group">
					<% @publication.attribute_values.each do |f| %>
						<li class="list-group-item">
							<strong>
							<%= f.publication_attribute.name %>:
							</strong>
							<%= f.attribute_value %>
						</li>
					<% end %>
				</ul>
			<% else %>
				<div class="panel-body">Brak dodatkowych parametrów.</div>
			<% end %>
		</div>
	</div>
</div>

app/views/publications/show.html.erb
<h1> Informacje o publikacji </h1>
<div class ="row">
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<strong>Tytuł: </strong><%= @publication.title %>
			</div>
			
			<ul class="list-group">
			<li class="list-group-item"><strong>Typ: </strong><%= @publication.publication_subtype.full_name %></li>
			<li class="list-group-item"><strong>Opis: </strong><%= @publication.description %></li>
			<li class="list-group-item"><strong>Rok wydania: </strong><%= @publication.publish_at %></li>
			<% if @publication.zalacznik.exists? %>
			<li class="list-group-item">
				<strong>Wersja elektroniczna:</strong>
				<%= link_to "plik", @publication.zalacznik.url %>
			</li>
			<% end %>
			<li class="list-group-item">
				<strong> Lista autorów: </strong>
				<ul class="list-group">
					<% @publication.authors.each do |a| %>
						<li class="list-group-item">
							<strong><%= link_to "#{a.full_name}, ", a %></strong>
							<%= a.email %>
						</li>
					<% end %>
				</ul>
			</li>
			<li class="list-group-item"><strong>Dodane przez: </strong><%= "#{@publication.user.full_name} , #{@publication.user.email}" %></li>
			<li class="list-group-item"><strong>Data dodania: </strong><%= @publication.created_at %></li>
			<li class="list-group-item"><strong>Data aktualizacji: </strong><%= @publication.updated_at %></li>
			</ul>

			<div class="panel-footer">
				<%= link_to 'Lista wszystkich publikacji', publications_path, 
					class: " label label-primary" %>
				<span class="label label-primary pull-right">
				<%= link_to fa_icon("edit", text: "Edytuj"), edit_publication_path(@publication) if can? :edit , @publication %>
			    <%= link_to fa_icon("remove", text: "Usuń"), @publication, method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy , @publication %>
			    <%= link_to fa_icon("file-pdf-o", text: "PDF"), publication_path(@publication, :format=> :pdf) %>
			     <%= link_to fa_icon("file-word-o", text: "DOCX"), publication_path(@publication, :format=> :docx) %>
			     </span>
			</div>
			
		</div>
	</div>

	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				Dodatkowe parametry
			</div>
			<% if @publication.attribute_values.any? %>
				<ul class="list-group">
					<% @publication.attribute_values.each do |f| %>
						<li class="list-group-item">
							<strong>
							<%= f.publication_attribute.name %>:
							</strong>
							<%= f.attribute_value %>
						</li>
					<% end %>
				</ul>
			<% else %>
				<div class="panel-body">Brak dodatkowych parametrów.</div>
			<% end %>
		</div>
	</div>
</div>