config/routes.rb
Rails.application.routes.draw do

  
  root 'static_pages#index'
  resources :publication_types
  resources :publications , except: :destroy
  resources :publication_subtypes
  resources :publication_attributes
  resources :authors

  get 'admin/users/index' , to: 'admins#users' , as: :users_administrator
  delete 'admin/users/:id/destroy' , to: 'admins#destroy_user' , as: :admin_destroy_user
  get 'admin/users/:id/edit', to: 'admins#edit_user' , as: :admin_edit_user
  patch 'admin/users/:id' , to: 'admins#update_user' , as: :admin_user

  match 'attributes/:subtype/:publication' , to: 'publications#params_list' , via: 'get'
  match 'attributes/:subtype' , to: 'publications#params_list_new', via: 'get'
  devise_for :users , controllers: {registrations: "users/registrations"}

end

app/controllers/publication_types_controller.rb
class PublicationTypesController < ApplicationController
  before_action :set_publication_type, only: [:show, :edit, :update, :destroy]

  # GET /publication_types
  # GET /publication_types.json
  def index
    @publication_types = PublicationType.all.order("name ASC")
  end

  # GET /publication_types/1
  # GET /publication_types/1.json
  def show
  end

  # GET /publication_types/new
  def new
    authorize! :create , PublicationType
    @publication_type = PublicationType.new
    @attrs = PublicationAttribute.prepare_select_array
    @selected = []
  end

  # GET /publication_types/1/edit
  def edit
    authorize! :edit , @publication_type
    @attrs = PublicationAttribute.prepare_select_array
    @selected = @publication_type.publication_attributes.pluck(:id)
  end

  # POST /publication_types
  # POST /publication_types.json
  def create
    authorize! :create , PublicationType
    @publication_type = PublicationType.new(publication_type_params)
    @publication_type.publication_attributes = attributes_list_param
    respond_to do |format|
      if @publication_type.save
        format.html { redirect_to @publication_type, notice: 'Publication type was successfully created.' }
        format.json { render :show, status: :created, location: @publication_type }
      else
        @attrs = PublicationAttribute.prepare_select_array
        @selected = params[:publication_type][:publication_attributes][:id]
        format.html { render :new }
        format.json { render json: @publication_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publication_types/1
  # PATCH/PUT /publication_types/1.json
  def update
    authorize! :edit , @publication_type
    @publication_type.publication_attributes = attributes_list_param
    respond_to do |format|
      if @publication_type.update(publication_type_params)
        format.html { redirect_to @publication_type, notice: 'Publication type was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication_type }
      else
        @attrs = PublicationAttribute.prepare_select_array
        @selected = params[:publication_type][:publication_attributes][:id]
        format.html { render :edit }
        format.json { render json: @publication_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publication_types/1
  # DELETE /publication_types/1.json
  def destroy
    authorize! :destroy , @publication_type
    @publication_type.destroy
    respond_to do |format|
      format.html { redirect_to publication_types_url, notice: 'Publication type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication_type
      @publication_type = PublicationType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_type_params
       params.require(:publication_type).permit(:name)
    end

    def attributes_list_param
      PublicationAttribute.where(id: params[:publication_type][:publication_attributes][:id])
    end
end

app/helpers/publication_types_helper.rb
module PublicationTypesHelper
end

app/views/publication_types/_form.html.erb
<div class = "row">
	<div class="col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading">
				<%= title %>
			</div>
			<div class="panel-body">
				<%= bootstrap_form_for(@publication_type) do |f| %>
				  <%= f.error_summary %>
				  <%= f.text_field :name , label: "Nazwa" , required: true %>
				  <%= f.fields_for :publication_attributes do |a| %>
				  	<%= a.select(:id,options_for_select(@attrs,@selected),{label: "Atrybuty"},{multiple: true,:id=>"attributes"} )%>
				  <% end %>  
				  <%= f.submit "Zapisz" , class: "btn btn-primary" %>
				<% end %>
			</div>
			<div class="panel-footer">
				<%= link_to 'Powrót', publication_types_path, class: "label label-primary" %>
			</div>
		</div>
	</div>
</div>


<!--  -->

app/views/publication_types/edit.html.erb
<h1>Edycja</h1>
<%= render partial: 'form' , locals: {title: @publication_type.name} %>

app/views/publication_types/index.html.erb
<h1>Lista typów publikacji</h1>
<div class="row">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <strong>Liczba typów: <%= @publication_types.count %></strong>
        <%= link_to 'Nowy typ', new_publication_type_path ,class: "label label-success pull-right" if can? :create , PublicationType %>
      </div>
      <ul class="list-group">
          <% @publication_types.each do |p| %>
            <li class="list-group-item">
              <%= link_to p.name , p %>
              <%= link_to 'Pokaż', publication_type_path(p) ,class: "label label-primary pull-right" %>
              <%= link_to 'Edytuj', edit_publication_type_path(p) ,class: "label label-default pull-right" if can? :edit , p %>
              <%= link_to 'Usuń', p, method: :delete, data: { confirm: 'Are you sure?' } ,class: "label label-primary pull-right" if can? :destroy , p %>
            </li>
         <% end %>
      </ul>
      <div class="panel-footer">
      </div>
    </div>
  </div>
</div>



<!--  -->

app/views/publication_types/new.html.erb
<h1>Nowy typ publikacji</h1>

<%= render partial: 'form' , locals: {title: "Dane dla nowego typu publikacji" }%>

app/views/publication_types/show.html.erb
<h1><%= @publication_type.name %></h1>
<div class = "row">
	<div class="col-md-8">
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="row">
					<div class="col-md-6">
						<h4> Lista atrybutów </h4>
						<ul>
							<% @publication_type.publication_attributes.each do |a| %>
								<li><%= a.name %></li>
							<% end %>
						</ul>
					</div>
					<div class="col-md-6">
						<h4> Dostępne podtypy </h4>
						<% if @publication_type.publication_subtypes.count > 0 %>
							<ul>
								<% @publication_type.publication_subtypes.each do |a| %>
									<li><%= link_to a.name , a %></li>
								<% end %>
							</ul>
						<% else %>
							Brak
						<% end %>
					</div>
				</div>
			</div>
			<div class="panel-footer">
				<%= link_to 'Lista typów', publication_types_path %>
				<%= link_to edit_publication_type_path(@publication_type), class: "pull-right label label-primary" do %>
					<span>Edytuj</span>
				<% end %>
			</div>
		</div>
	</div>
</div>